---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wujiayu.
--- DateTime: 2018/12/5 7:51 PM
---
local TAG = "MLDataCard"
local yogaBuilder = function(container)
    container.isEnabled = true
    container.alignItems = YGAlignFlexStart
    container.flexDirection = YGFlexDirectionColumn --垂直布局

    local backgroundIv = container.addImageView()      --取值->添加图层关系： addImageView()
    backgroundIv.isEnabled = true
    backgroundIv.width = 334
    backgroundIv.height = 180
    backgroundIv.imagePath = 'tools_card_ml.png'
    backgroundIv.marginStart = 13

    local allContentContainer = container.addContainer()
    allContentContainer.width = 334
    allContentContainer.height = 180
    allContentContainer.marginStart = 13
    allContentContainer.marginTop = -180
    allContentContainer.alignItems = YGAlignFlexStart
    allContentContainer.flexDirection = YGFlexDirectionColumn

    local titleContainer = allContentContainer.addContainer()
    titleContainer.width = 334
    titleContainer.height = 45
    titleContainer.isEnabled = true
    titleContainer.alignItems = YGAlignCenter
    titleContainer.flexDirection = YGFlexDirectionColumn
    titleContainer.marginStart = 13
    titleContainer.marginTop = 14

    local titleTv = titleContainer.addTextView()
    titleTv.width = 300
    titleTv.height = 20
    titleTv.text = "Mobile Legends"
    titleTv.textTable = {
        fontSize = 16,
        isBold = false,
        alignment = TextAlignmentCenter,
        color = { a = 1.0, r = 1.0, g = 1.0, b = 1.0 }
    }

    local userInfoContainer = allContentContainer.addContainer()
    userInfoContainer.isEnabled = true
    userInfoContainer.width = 334
    userInfoContainer.height = 66
    userInfoContainer.alignItems = YGAlignFlexStart
    userInfoContainer.flexDirection = YGFlexDirectionRow
    userInfoContainer.marginStart = 13

    local userAvatarIv = userInfoContainer.addImageView()
    userAvatarIv.width = 46
    userAvatarIv.height = 46
    userAvatarIv.viewCornerRadius = 23
    userAvatarIv.imagePath = 'zz.png'
    userAvatarIv.marginStart = 16

    local userNameContainer = userInfoContainer.addContainer()
    userNameContainer.width = 172
    userNameContainer.height = 36
    userNameContainer.alignItems = YGAlignFlexStart
    userNameContainer.flexDirection = YGFlexDirectionColumn
    userNameContainer.marginStart = 9
    userNameContainer.marginTop = 2

    local userNameTv = userNameContainer.addTextView()
    userNameTv.width = 172
    userNameTv.height = 18
    userNameTv.text = "Gary Wu"
    userNameTv.textTable = {
        fontSize = 15,
        isBold = false,
        alignment = TextAlignmentLeft,
        color = { a = 1.0, r = 1.0, g = 1.0, b = 1.0 },
        numberOfLines = 1
    }

    local nearlyStatusContainer = userNameContainer.addContainer()
    nearlyStatusContainer.width = 172
    nearlyStatusContainer.height = 14
    nearlyStatusContainer.marginTop = 2
    nearlyStatusContainer.alignItems = YGAlignCenter
    nearlyStatusContainer.flexDirection = YGFlexDirectionRow

    local nearlyStatusIv = nearlyStatusContainer.addImageView()
    nearlyStatusIv.width = 12
    nearlyStatusIv.height = 12
    nearlyStatusIv.imagePath = "stars_rise.png"

    local nearlyStatusTv = nearlyStatusContainer.addTextView()
    nearlyStatusTv.width = 172
    nearlyStatusTv.height = 18
    nearlyStatusTv.text = "Nearly status:" .. " " .. "5" .. " " .. "stars"
    nearlyStatusTv.textTable = {
        fontSize = 12,
        isBold = false,
        alignment = TextAlignmentLeft,
        color = { a = 0.6, r = 1.0, g = 1.0, b = 1.0 }
    }

    local rankContainer = userInfoContainer.addContainer()
    rankContainer.width = 60
    rankContainer.height = 64
    rankContainer.marginStart = 13
    rankContainer.alignItems = YGAlignFlexStart
    rankContainer.flexDirection = YGFlexDirectionColumn

    local rankBgIv = rankContainer.addImageView()
    rankBgIv.width = 60
    rankBgIv.height = 52
    rankBgIv.imagePath = "rank_4.png"

    local rankIv = rankContainer.addImageView()
    rankIv.width = 60
    rankIv.height = 52
    rankIv.marginTop = -52
    rankIv.imagePath = "rank_master.png"

    local starsContainer = rankContainer.addContainer()
    starsContainer.width = 60
    starsContainer.height = 9
    starsContainer.alignItems = YGAlignFlexStart
    starsContainer.flexDirection = YGFlexDirectionRow
    starsContainer.justifyContent = YGJustifyCenter

    local starsIv = starsContainer.addImageView()
    starsIv.width = 9
    starsIv.height = 9
    starsIv.imagePath = "star.png"

    local dataContainer = allContentContainer.addContainer()
    dataContainer.width = 334
    dataContainer.height = 40
    dataContainer.marginStart = 19
    dataContainer.alignItems = YGAlignFlexStart
    dataContainer.justifyContent = YGJustifySpaceBetween
    dataContainer.flexDirection = YGFlexDirectionRow

    local dataSubContainerWidth = 82
    local dataSubContainerHeight = 40
    local textViewWidth = 70
    local textValueHeight = 22
    local textTipHeight = 14
    local dataSubContainerAlignItems = YGAlignFlexStart
    local dataSubContainerFlexDirection = YGFlexDirectionColumn
    local subContainerTextTable_Value = {
        fontSize = 18,
        alignment = TextAlignmentCenter,
        fontName = "DIN-Bold.otf",
        color = { a = 1.0, r = 1.0, g = 1.0, b = 1.0 }
    }

    local subContainerTextTable_Tip = {
        fontSize = 12,
        alignment = TextAlignmentCenter,
        color = { a = 0.6, r = 1.0, g = 1.0, b = 1.0 }
    }

    local sessionsContainer = dataContainer.addContainer()
    sessionsContainer.width = dataSubContainerWidth
    sessionsContainer.height = dataSubContainerHeight
    sessionsContainer.alignItems = dataSubContainerAlignItems
    sessionsContainer.flexDirection = dataSubContainerFlexDirection

    local sessionsValueTv = sessionsContainer.addTextView()
    sessionsValueTv.width = textViewWidth
    sessionsValueTv.height = textValueHeight
    sessionsValueTv.text = "1490"
    sessionsValueTv.textTable = subContainerTextTable_Value

    local sessionsTv = sessionsContainer.addTextView()
    sessionsTv.width = textViewWidth
    sessionsTv.height = textTipHeight
    sessionsTv.marginTop = 1
    sessionsTv.text = "Sessions"
    sessionsTv.textTable = subContainerTextTable_Tip


    local winRateContainer = dataContainer.addContainer()
    winRateContainer.width = dataSubContainerWidth
    winRateContainer.height = dataSubContainerHeight
    winRateContainer.alignItems = dataSubContainerAlignItems
    winRateContainer.flexDirection = dataSubContainerFlexDirection

    local winRateValueTv = winRateContainer.addTextView()
    winRateValueTv.width = textViewWidth
    winRateValueTv.height = textValueHeight
    winRateValueTv.text = "49" .. "%"
    winRateValueTv.textTable = subContainerTextTable_Value

    local winRateTv = winRateContainer.addTextView()
    winRateTv.width = textViewWidth
    winRateTv.height = textTipHeight
    winRateTv.marginTop = 1
    winRateTv.text = "Win"
    winRateTv.textTable = subContainerTextTable_Tip

    local mvpContainer = dataContainer.addContainer()
    mvpContainer.width = dataSubContainerWidth
    mvpContainer.height = dataSubContainerHeight
    mvpContainer.alignItems = dataSubContainerAlignItems
    mvpContainer.flexDirection = dataSubContainerFlexDirection

    local mvpValueTv = mvpContainer.addTextView()
    mvpValueTv.width = textViewWidth
    mvpValueTv.height = textValueHeight
    mvpValueTv.text = "398"
    mvpValueTv.textTable = subContainerTextTable_Value

    local mvpTv = mvpContainer.addTextView()
    mvpTv.width = textViewWidth
    mvpTv.height = textTipHeight
    mvpTv.marginTop = 1
    mvpTv.text = "MVP"
    mvpTv.textTable = subContainerTextTable_Tip

    local powerContainer = dataContainer.addContainer()
    powerContainer.width = dataSubContainerWidth
    powerContainer.height = dataSubContainerHeight
    powerContainer.alignItems = dataSubContainerAlignItems
    powerContainer.flexDirection = dataSubContainerFlexDirection

    local powerValueTv = powerContainer.addTextView()
    powerValueTv.width = textViewWidth
    powerValueTv.height = textValueHeight
    powerValueTv.marginStart = -6
    powerValueTv.text = "7878"
    powerValueTv.textTable = subContainerTextTable_Value

    local powerTv = powerContainer.addTextView()
    powerTv.width = textViewWidth
    powerTv.height = textTipHeight
    powerTv.marginStart = -6
    powerTv.text = "Power"
    powerTv.textTable = subContainerTextTable_Tip

end

return yogaBuilder