---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wujiayu.
--- DateTime: 2018/12/5 7:51 PM
---
local TAG = "MLNoDataCard"
local yogaBuilder = function(container)
    container.isEnabled = true
    container.alignItems = YGAlignFlexStart
    container.flexDirection = YGFlexDirectionColumn --垂直布局

    -- ImageView 相关
    local backgroundIv = container.addImageView()      --取值->添加图层关系： addImageView()
    backgroundIv.isEnabled = true
    backgroundIv.width = 334
    backgroundIv.height = 180
    backgroundIv.imagePath = 'zz.png'
    backgroundIv.marginStart = 13

    local tvContainer = container.addContainer()
    tvContainer.isEnabled = true
    tvContainer.alignItems = YGAlignFlexStart
    tvContainer.flexDirection = YGFlexDirectionColumn --垂直布局
    tvContainer.width = 334 * 0.8
    tvContainer.height = 54
    tvContainer.marginStart = 33
    tvContainer.marginTop = -28

    local titleTv = tvContainer.addTextView()
    titleTv.isEnabled = true
    titleTv.width = 334 * 0.8
    titleTv.height = 21
    titleTv.text = 'MOBILE LEGENDS'
    titleTv.textTable = { color = { a = 1.0, r = 1.0, g = 1.0, b = 1.0 },
                          fontSize = 18,
                          alignment = TextAlignmentLeft,
                          isBold = true }

    local descriptionTv = tvContainer.addTextView()
    descriptionTv.width = 334 * 0.8
    descriptionTv.height = 30
    descriptionTv.isEnabled = true
    descriptionTv.marginTop = 1
    descriptionTv.text = '专业的数据分析体系，让你了解你的全面数据'
    descriptionTv.textTable = {
        fontSize = 12,
        isBold = false,
        alignment = TextAlignmentLeft,
        color = { r = 0.5, g = 0.5, b = 0.5, a = 1.0 }
    }
end

return yogaBuilder