---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wujiayu.
--- DateTime: 2018/12/7 8:39 PM
---
local notification = {}

notification.postNotification = function()
    print("testNotification postNotification1111")
    lua_notification.postNotification(3,
            {
                nickName = "lua123"
            })
end

notification.testPost = function()
    print("testNotification testPost")
    lua_thread.postToThread(BusinessThreadLOGIC, "testNotification", "postNotification")
end

return notification