/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flua_luayoga_YogaView */
#ifndef _Included_com_flua_luayoga_YogaView
#define _Included_com_flua_luayoga_YogaView

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_flua_luayoga_YogaView_loadLua
  (JNIEnv *, jobject, jstring);


JNIEXPORT void JNICALL Java_com_flua_luayoga_YogaView_dispose
  (JNIEnv *, jobject , jlong);

#ifdef __cplusplus
}
#endif
#endif
