/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_luakit_yoganode_YogaLayoutHelper */
#ifndef _Included_com_common_luakit_yoganode_YogaLayoutHelper
#define _Included_com_common_luakit_yoganode_YogaLayoutHelper

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_common_luakit_yoganode_YogaLayoutHelper_getItemcount
  (JNIEnv *, jobject, jlong);


JNIEXPORT jlong JNICALL Java_com_common_luakit_yoganode_YogaLayoutHelper_getItemViewType
  (JNIEnv *, jobject, jlong, jint);

JNIEXPORT void * JNICALL Java_com_common_luakit_yoganode_YogaLayoutHelper_onCreateView
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
