/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_luakit_yoganode_YogaLayoutHelper */
#ifndef _Included_com_common_luakit_yoganode_YogaLayoutHelper
#define _Included_com_common_luakit_yoganode_YogaLayoutHelper

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_common_luakit_yoganode_YogaLayoutHelper_getItemcount
  (JNIEnv *, jobject, jint, jlong, jlong);


JNIEXPORT jstring JNICALL Java_com_common_luakit_yoganode_YogaLayoutHelper_getItemViewType
  (JNIEnv *, jobject, jlong, jlong, jint);

JNIEXPORT jfloat JNICALL Java_com_common_luakit_yoganode_YogaLayoutHelper_getItemHeight
  (JNIEnv *, jobject, jlong, jlong, jint);

JNIEXPORT void JNICALL Java_com_common_luakit_yoganode_YogaLayoutHelper_onCreateView
  (JNIEnv *, jobject, jlong, jlong, jobject);

JNIEXPORT jobject JNICALL Java_com_common_luakit_yoganode_YogaLayoutHelper_onBindView
  (JNIEnv *, jobject, jlong, jlong, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
