/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_luakit_YogaView */
#ifndef _Included_com_common_luakit_YogaView
#define _Included_com_common_luakit_YogaView

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_common_luakit_YogaView_loadLua
  (JNIEnv *, jobject, jstring);


JNIEXPORT void JNICALL Java_com_common_luakit_YogaView_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
